# pages:
#   stage: deploy
#   script:
#     - mkdir .public
#     - cp -r ./docs/.vuepress/dist .public
#     - mv .public public
#   artifacts:
#     paths:
#       - public
#   only:
#     - master